const POSITIONS_DATA = {
  "schema_notes": {
    "category_values": [
      "Anal",
      "From Behind",
      "Man on Top",
      "Oral",
      "Sideways",
      "Sitting & Kneeling",
      "Solo",
      "Standing",
      "Woman on Top"
    ],
    "scale_1_5": "1 = lowest/least, 5 = highest/most",
    "condom_slip_risk": [
      "low",
      "medium",
      "high"
    ],
    "flexibility_required": [
      "low",
      "medium",
      "high"
    ],
    "pregnancy_suitability": [
      "not_suitable",
      "early_pregnancy_only",
      "until_mid_pregnancy",
      "safe_all_trimesters",
      "case_by_case"
    ],
    "boolean_fields": [
      "postpartum_recovery_suitability",
      "mobility_limitation_suitability",
      "pain_condition_recommended",
      "kissing_possible"
    ],
    "good_medium_poor_fields": [
      "vaginismus_dyspareunia_suitability",
      "erectile_difficulty_suitability",
      "long_penis_suitability",
      "short_penis_suitability",
      "premature_ejaculation_suitability"
    ],
    "privacy_noise_level": [
      "low",
      "medium",
      "high"
    ],
    "experience_level": [
      "beginner",
      "intermediate",
      "advanced"
    ],
    "penetration_control": [
      "male",
      "female",
      "shared",
      "self"
    ],
    "equipment_needed": [
      "none",
      "bed_edge",
      "chair",
      "wall_support",
      "pillow",
      "other"
    ],
    "disclaimer": "These are estimated design/prototype scores, not medical advice. Expert/clinical review is recommended before shipping in a real app. Category header rows from the original list (e.g. 'Shower Sex Positions') were section labels, not individual positions, so they were excluded from scoring."
  },
  "category_headers_excluded": [
    "Non-Penetrative Sex Positions",
    "Elevated Sex Positions",
    "Shower Sex Positions",
    "Bondage Sex Positions",
    "Car Sex Positions",
    "Masturbation Sex Positions",
    "Flat Sex Positions",
    "Blindfolded Sex Positions",
    "Cowboy Sex Positions",
    "Beach-Inspired Sex Positions",
    "Best Sex Positions For Vaginal Orgasm",
    "Creative Sex Positions"
  ],
  "positions": [
    {
      "name": "Modified Coital Alignment Technique",
      "category": "Man on Top",
      "deep_penetration": 2,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 5,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 4,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "CAT technique; body is shifted upward for sustained clitoral contact.",
      "photopath": "./positions/modified-coital-alignment-technique/modified-coital-alignment-technique.png"
    },
    {
      "name": "Missionary",
      "category": "Man on Top",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 3,
      "female_effort": 1,
      "lower_back_load": 2,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 3,
      "pregnancy_suitability": "trimester_1_only",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "low",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "photopath": "./positions/missionary/missionary.png"
    },
    {
      "name": "Doggy Style",
      "category": "From Behind",
      "deep_penetration": 5,
      "penetration_control": "male",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 3,
      "knee_load": 4,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/doggy-style/doggy-style.png"
    },
    {
      "name": "Pushing Tush",
      "category": "From Behind",
      "deep_penetration": 5,
      "penetration_control": "shared",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 3,
      "female_effort": 4,
      "lower_back_load": 3,
      "knee_load": 4,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Woman pushes her hips back; pacing partly controlled by her.",
      "photopath": "./positions/pushing-tush/pushing-tush.png"
    },
    {
      "name": "Rocking Horse",
      "category": "Woman on Top",
      "deep_penetration": 4,
      "penetration_control": "female",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 2,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "Rocking motion dominates; shallower depth variation.",
      "photopath": "./positions/rocking-horse/rocking-horse.png"
    },
    {
      "name": "Seated Scissors",
      "category": "Sideways",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 1,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 3,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "poor",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "good",
      "eye_contact_intimacy": 4,
      "kissing_possible": false,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "",
      "photopath": "./positions/seated-scissors/seated-scissors.png"
    },
    {
      "name": "Spooning",
      "category": "Sideways",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 2,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 5,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 2,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/spooning/spooning.png"
    },
    {
      "name": "Scissoring",
      "category": "Sideways",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 1,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 2,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "poor",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "good",
      "eye_contact_intimacy": 4,
      "kissing_possible": false,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "",
      "photopath": "./positions/scissoring/scissoring.png"
    },
    {
      "name": "Bend Over Baby",
      "category": "From Behind",
      "deep_penetration": 5,
      "penetration_control": "male",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 3,
      "knee_load": 4,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "bed_edge",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/bend-over-baby/bend-over-baby.png"
    },
    {
      "name": "Scissors",
      "category": "Sideways",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 1,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "poor",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "good",
      "eye_contact_intimacy": 4,
      "kissing_possible": false,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "",
      "photopath": "./positions/scissors/scissors.png"
    },
    {
      "name": "Uncloak the Clitoris",
      "category": "Oral",
      "deep_penetration": 1,
      "penetration_control": "shared",
      "g_spot_stimulation": 1,
      "clitoral_stimulation": 5,
      "condom_slip_risk": "low",
      "male_effort": 2,
      "female_effort": 2,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 5,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "good",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/uncloak-the-clitoris/uncloak-the-clitoris.png"
    },
    {
      "name": "Baring the Scepter",
      "category": "Oral",
      "deep_penetration": 1,
      "penetration_control": "shared",
      "g_spot_stimulation": 1,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "low",
      "male_effort": 2,
      "female_effort": 2,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 5,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "good",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Male-focused manual/oral stimulation position.",
      "photopath": "./positions/baring-the-scepter/baring-the-scepter.png"
    },
    {
      "name": "Self Loving On Your Knees",
      "category": "Solo",
      "deep_penetration": 1,
      "penetration_control": "self",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "low",
      "male_effort": 1,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 1,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/self-loving-on-your-knees/self-loving-on-your-knees.png"
    },
    {
      "name": "Queening in Bondage",
      "category": "Oral",
      "deep_penetration": 3,
      "penetration_control": "female",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 5,
      "condom_slip_risk": "medium",
      "male_effort": 3,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 2,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "advanced",
      "note": "Oral-focused position combined with restraint.",
      "photopath": "./positions/queening-in-bondage/queening-in-bondage.png"
    },
    {
      "name": "Countertop",
      "category": "Standing",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "high",
      "male_effort": 4,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 1,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "advanced",
      "note": "Seated on a counter rather than fully standing.",
      "photopath": "./positions/countertop/countertop.png"
    },
    {
      "name": "Happy Scissors",
      "category": "Sideways",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 1,
      "clitoral_stimulation": 5,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 2,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "poor",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "good",
      "eye_contact_intimacy": 4,
      "kissing_possible": false,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "",
      "photopath": "./positions/happy-scissors/happy-scissors.png"
    },
    {
      "name": "The Butterfly",
      "category": "Standing",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "high",
      "male_effort": 4,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 1,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "advanced",
      "note": "Woman lies on her back at edge of a table/counter, man stands.",
      "photopath": "./positions/the-butterfly/the-butterfly.png"
    },
    {
      "name": "Lap Dance",
      "category": "Woman on Top",
      "deep_penetration": 4,
      "penetration_control": "female",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "intermediate",
      "note": "Performed seated on a chair.",
      "photopath": "./positions/lap-dance/lap-dance.png"
    },
    {
      "name": "Standing Up Full Frontal",
      "category": "Standing",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "high",
      "male_effort": 4,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 1,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "medium",
      "equipment_needed": "wall_support",
      "experience_level": "advanced",
      "note": "",
      "photopath": "./positions/standing-up-full-frontal/standing-up-full-frontal.png"
    },
    {
      "name": "Soap N Grope",
      "category": "Standing",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "high",
      "male_effort": 3,
      "female_effort": 3,
      "lower_back_load": 2,
      "knee_load": 1,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "case_by_case",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "low",
      "equipment_needed": "other",
      "experience_level": "intermediate",
      "note": "",
      "photopath": "./positions/soap-n-grope/soap-n-grope.png"
    },
    {
      "name": "Hands Behind Ankles",
      "category": "From Behind",
      "deep_penetration": 5,
      "penetration_control": "male",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 4,
      "lower_back_load": 3,
      "knee_load": 4,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "Woman holds her own ankles; requires high flexibility.",
      "photopath": "./positions/hands-behind-ankles/hands-behind-ankles.png"
    },
    {
      "name": "The Kinky Missionary",
      "category": "Man on Top",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 4,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "beginner",
      "note": "Missionary variant with added restraint/accessories.",
      "photopath": "./positions/the-kinky-missionary/the-kinky-missionary.png"
    },
    {
      "name": "Standing Room Only",
      "category": "Standing",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "high",
      "male_effort": 4,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 1,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "medium",
      "equipment_needed": "wall_support",
      "experience_level": "advanced",
      "note": "",
      "photopath": "./positions/standing-room-only/standing-room-only.png"
    },
    {
      "name": "Backseat Driver",
      "category": "Woman on Top",
      "deep_penetration": 4,
      "penetration_control": "female",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "intermediate",
      "note": "Woman on top in a car's back seat.",
      "photopath": "./positions/backseat-driver/backseat-driver.png"
    },
    {
      "name": "Belt Bondage",
      "category": "Sitting & Kneeling",
      "deep_penetration": 3,
      "penetration_control": "shared",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "medium",
      "male_effort": 3,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 2,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "advanced",
      "note": "",
      "photopath": "./positions/belt-bondage/belt-bondage.png"
    },
    {
      "name": "Seated Rear Entry",
      "category": "Sitting & Kneeling",
      "deep_penetration": 5,
      "penetration_control": "male",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 3,
      "female_effort": 2,
      "lower_back_load": 3,
      "knee_load": 1,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "chair",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/seated-rear-entry/seated-rear-entry.png"
    },
    {
      "name": "Yab Yum",
      "category": "Sitting & Kneeling",
      "deep_penetration": 2,
      "penetration_control": "female",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 2,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "Face-to-face seated position; high intimacy, slow pace.",
      "photopath": "./positions/yab-yum/yab-yum.png"
    },
    {
      "name": "Trunk Space",
      "category": "From Behind",
      "deep_penetration": 3,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 3,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 2,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "low",
      "equipment_needed": "other",
      "experience_level": "intermediate",
      "note": "Performed on a car trunk/hood.",
      "photopath": "./positions/trunk-space/trunk-space.png"
    },
    {
      "name": "Over the Hump",
      "category": "Solo",
      "deep_penetration": 1,
      "penetration_control": "self",
      "g_spot_stimulation": 1,
      "clitoral_stimulation": 5,
      "condom_slip_risk": "low",
      "male_effort": 1,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 1,
      "privacy_noise_level": "medium",
      "equipment_needed": "pillow",
      "experience_level": "beginner",
      "note": "Solo stimulation over a pillow or object.",
      "photopath": "./positions/over-the-hump/over-the-hump.png"
    },
    {
      "name": "Superstar",
      "category": "Solo",
      "deep_penetration": 2,
      "penetration_control": "self",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "low",
      "male_effort": 1,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 1,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/superstar/superstar.png"
    },
    {
      "name": "The Solo Snake",
      "category": "Solo",
      "deep_penetration": 1,
      "penetration_control": "self",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "low",
      "male_effort": 1,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 4,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 1,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/the-solo-snake/the-solo-snake.png"
    },
    {
      "name": "Opening Up",
      "category": "Oral",
      "deep_penetration": 1,
      "penetration_control": "shared",
      "g_spot_stimulation": 1,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "low",
      "male_effort": 2,
      "female_effort": 2,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 5,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "good",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Foreplay/opening-focused position.",
      "photopath": "./positions/opening-up/opening-up.png"
    },
    {
      "name": "69",
      "category": "Oral",
      "deep_penetration": 1,
      "penetration_control": "self",
      "g_spot_stimulation": 1,
      "clitoral_stimulation": 5,
      "condom_slip_risk": "low",
      "male_effort": 2,
      "female_effort": 2,
      "lower_back_load": 2,
      "knee_load": 1,
      "shoulder_wrist_load": 2,
      "neck_load": 2,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "good",
      "eye_contact_intimacy": 2,
      "kissing_possible": false,
      "communication_ease": 3,
      "privacy_noise_level": "low",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/69/69.png"
    },
    {
      "name": "Layer Cake",
      "category": "Man on Top",
      "deep_penetration": 2,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 4,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Flat, horizontal, low-intensity missionary variant.",
      "photopath": "./positions/layer-cake/layer-cake.png"
    },
    {
      "name": "The Reverse Slither",
      "category": "From Behind",
      "deep_penetration": 3,
      "penetration_control": "shared",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 4,
      "lower_back_load": 4,
      "knee_load": 3,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 1,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "Reverse-direction sliding entry variant.",
      "photopath": "./positions/the-reverse-slither/the-reverse-slither.png"
    },
    {
      "name": "Stacked Snakes",
      "category": "Man on Top",
      "deep_penetration": 2,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 3,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Both bodies flat and horizontally stacked; legs interlocked for reduced strain.",
      "photopath": "./positions/stacked-snakes/stacked-snakes.png"
    },
    {
      "name": "Anal Spoon",
      "category": "Anal",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 2,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 5,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 2,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Anal-focused spooning variant; requires extra preparation and slower pace.",
      "photopath": "./positions/anal-spoon/anal-spoon.png"
    },
    {
      "name": "The Splitting of Bamboo",
      "category": "Man on Top",
      "deep_penetration": 5,
      "penetration_control": "shared",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 4,
      "lower_back_load": 4,
      "knee_load": 3,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 1,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "One leg raised over the shoulder; requires high flexibility.",
      "photopath": "./positions/the-splitting-of-bamboo/the-splitting-of-bamboo.png"
    },
    {
      "name": "The Private Dancer",
      "category": "Woman on Top",
      "deep_penetration": 4,
      "penetration_control": "female",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "chair",
      "experience_level": "intermediate",
      "note": "",
      "photopath": "./positions/the-private-dancer/the-private-dancer.png"
    },
    {
      "name": "X Marks the Spot",
      "category": "Man on Top",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 4,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "Legs crossed to form an X shape.",
      "photopath": "./positions/x-marks-the-spot/x-marks-the-spot.png"
    },
    {
      "name": "Rock n Roll",
      "category": "Woman on Top",
      "deep_penetration": 4,
      "penetration_control": "shared",
      "g_spot_stimulation": 4,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 4,
      "lower_back_load": 4,
      "knee_load": 3,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 1,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "Rhythmic rocking motion dominates this creative variant; rocking increases G-spot stimulation.",
      "photopath": "./positions/rock-n-roll/rock-n-roll.png"
    },
    {
      "name": "Cowgirl or Cowboy",
      "category": "Woman on Top",
      "deep_penetration": 4,
      "penetration_control": "female",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "",
      "photopath": "./positions/cowgirl-or-cowboy/cowgirl-or-cowboy.png"
    },
    {
      "name": "Face to Face",
      "category": "Man on Top",
      "deep_penetration": 2,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 2,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "pillow",
      "experience_level": "beginner",
      "note": "Face-to-face, seated or side-lying; pillow support recommended for side-lying variant.",
      "photopath": "./positions/face-to-face/face-to-face.png"
    },
    {
      "name": "Missionary With a Twist",
      "category": "Man on Top",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 4,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "pillow",
      "experience_level": "beginner",
      "note": "Pillow under hips or altered leg angle added.",
      "photopath": "./positions/missionary-with-a-twist/missionary-with-a-twist.png"
    },
    {
      "name": "On the Stomach",
      "category": "From Behind",
      "deep_penetration": 2,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 1,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Woman lies flat on her stomach with hips not raised; low effort required from her.",
      "photopath": "./positions/on-the-stomach/on-the-stomach.png"
    },
    {
      "name": "Spooning With a Twist",
      "category": "Sideways",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "low",
      "male_effort": 2,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 5,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 2,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Woman's top leg raised to change the angle.",
      "photopath": "./positions/spooning-with-a-twist/spooning-with-a-twist.png"
    },
    {
      "name": "The BBQ Quickie",
      "category": "Standing",
      "deep_penetration": 3,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 3,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 2,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "low",
      "equipment_needed": "other",
      "experience_level": "intermediate",
      "note": "Quick outdoor/beach position.",
      "photopath": "./positions/the-bbq-quickie/the-bbq-quickie.png"
    },
    {
      "name": "The Lounging Lioness",
      "category": "Woman on Top",
      "deep_penetration": 4,
      "penetration_control": "female",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 2,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "intermediate",
      "note": "Relaxed woman-on-top on a lounger/bed.",
      "photopath": "./positions/the-lounging-lioness/the-lounging-lioness.png"
    },
    {
      "name": "The Pouncing Panther",
      "category": "From Behind",
      "deep_penetration": 5,
      "penetration_control": "male",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 5,
      "female_effort": 2,
      "lower_back_load": 3,
      "knee_load": 5,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/the-pouncing-panther/the-pouncing-panther.png"
    },
    {
      "name": "The Teddy Bear",
      "category": "Sideways",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 2,
      "female_effort": 1,
      "lower_back_load": 1,
      "knee_load": 1,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 5,
      "pregnancy_suitability": "safe_all_trimesters",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": true,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 2,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Slow, cuddly variant.",
      "photopath": "./positions/the-teddy-bear/the-teddy-bear.png"
    },
    {
      "name": "Beach Safe Doggy Style",
      "category": "From Behind",
      "deep_penetration": 5,
      "penetration_control": "male",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 3,
      "knee_load": 4,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "beginner",
      "note": "A towel/mat under the knees is recommended.",
      "photopath": "./positions/beach-safe-doggy-style/beach-safe-doggy-style.png"
    },
    {
      "name": "In the Water",
      "category": "Standing",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "high",
      "male_effort": 3,
      "female_effort": 3,
      "lower_back_load": 2,
      "knee_load": 1,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "case_by_case",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "intermediate",
      "note": "",
      "photopath": "./positions/in-the-water/in-the-water.png"
    },
    {
      "name": "On a Beach Ball",
      "category": "Standing",
      "deep_penetration": 2,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "high",
      "male_effort": 3,
      "female_effort": 3,
      "lower_back_load": 2,
      "knee_load": 1,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 3,
      "pregnancy_suitability": "case_by_case",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "medium",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "medium",
      "equipment_needed": "other",
      "experience_level": "intermediate",
      "note": "",
      "photopath": "./positions/on-a-beach-ball/on-a-beach-ball.png"
    },
    {
      "name": "Reverse Cowgirl",
      "category": "Woman on Top",
      "deep_penetration": 4,
      "penetration_control": "female",
      "g_spot_stimulation": 4,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "Woman faces away from the man, changing the G-spot angle.",
      "photopath": "./positions/reverse-cowgirl/reverse-cowgirl.png"
    },
    {
      "name": "Standing Up",
      "category": "Standing",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "high",
      "male_effort": 4,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 1,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "medium",
      "equipment_needed": "wall_support",
      "experience_level": "advanced",
      "note": "",
      "photopath": "./positions/standing-up/standing-up.png"
    },
    {
      "name": "Under a Blanket",
      "category": "Man on Top",
      "deep_penetration": 2,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 4,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "low",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Classic variant with added privacy under a blanket.",
      "photopath": "./positions/under-a-blanket/under-a-blanket.png"
    },
    {
      "name": "Closed for Business",
      "category": "Man on Top",
      "deep_penetration": 3,
      "penetration_control": "shared",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 4,
      "lower_back_load": 4,
      "knee_load": 3,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 1,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "Legs held together for a tighter sensation.",
      "photopath": "./positions/closed-for-business/closed-for-business.png"
    },
    {
      "name": "In High Heels",
      "category": "Standing",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "high",
      "male_effort": 4,
      "female_effort": 3,
      "lower_back_load": 3,
      "knee_load": 1,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 3,
      "privacy_noise_level": "medium",
      "equipment_needed": "wall_support",
      "experience_level": "advanced",
      "note": "Standing variant with angle assisted by heels.",
      "photopath": "./positions/in-high-heels/in-high-heels.png"
    },
    {
      "name": "The Drop Box",
      "category": "From Behind",
      "deep_penetration": 5,
      "penetration_control": "shared",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 4,
      "lower_back_load": 4,
      "knee_load": 3,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 1,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "Woman leans forward for a deep angle.",
      "photopath": "./positions/the-drop-box/the-drop-box.png"
    },
    {
      "name": "The G Whiz",
      "category": "Man on Top",
      "deep_penetration": 4,
      "penetration_control": "male",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 3,
      "knee_load": 4,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "Focused on G-spot angle.",
      "photopath": "./positions/the-g-whiz/the-g-whiz.png"
    },
    {
      "name": "The Tilt-a-Whirl",
      "category": "Woman on Top",
      "deep_penetration": 4,
      "penetration_control": "female",
      "g_spot_stimulation": 4,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "Woman leans forward/back to change the angle.",
      "photopath": "./positions/the-tilt-a-whirl/the-tilt-a-whirl.png"
    },
    {
      "name": "The Circus Freak",
      "category": "Sitting & Kneeling",
      "deep_penetration": 3,
      "penetration_control": "shared",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 4,
      "lower_back_load": 4,
      "knee_load": 3,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 1,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "General/mixed stimulation combo position.",
      "photopath": "./positions/the-circus-freak/the-circus-freak.png"
    },
    {
      "name": "Froggie-Style",
      "category": "From Behind",
      "deep_penetration": 5,
      "penetration_control": "male",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 3,
      "knee_load": 4,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "Woman in a squatting frog-like position.",
      "photopath": "./positions/froggie-style/froggie-style.png"
    },
    {
      "name": "The Yogi",
      "category": "Man on Top",
      "deep_penetration": 5,
      "penetration_control": "shared",
      "g_spot_stimulation": 4,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 4,
      "lower_back_load": 4,
      "knee_load": 3,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 1,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "Similar to Splitting of Bamboo but more difficult; requires high flexibility.",
      "photopath": "./positions/the-yogi/the-yogi.png"
    },
    {
      "name": "Inverted Missionary",
      "category": "Man on Top",
      "deep_penetration": 4,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 4,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "Woman's hips raised in a missionary variant.",
      "photopath": "./positions/inverted-missionary/inverted-missionary.png"
    },
    {
      "name": "The Cowpoke",
      "category": "Woman on Top",
      "deep_penetration": 3,
      "penetration_control": "female",
      "g_spot_stimulation": 3,
      "clitoral_stimulation": 4,
      "condom_slip_risk": "medium",
      "male_effort": 1,
      "female_effort": 4,
      "lower_back_load": 2,
      "knee_load": 3,
      "shoulder_wrist_load": 1,
      "neck_load": 1,
      "flexibility_required": "medium",
      "overweight_suitability": 3,
      "pregnancy_suitability": "early_pregnancy_only",
      "postpartum_recovery_suitability": true,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "good",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "good",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 4,
      "kissing_possible": true,
      "communication_ease": 4,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "Woman leans forward while on top.",
      "photopath": "./positions/the-cowpoke/the-cowpoke.png"
    },
    {
      "name": "Field Goal",
      "category": "Man on Top",
      "deep_penetration": 3,
      "penetration_control": "male",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "low",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 4,
      "knee_load": 2,
      "shoulder_wrist_load": 3,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 2,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "medium",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "good",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 5,
      "kissing_possible": true,
      "communication_ease": 5,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "advanced",
      "note": "Legs raised toward the shoulders.",
      "photopath": "./positions/field-goal/field-goal.png"
    },
    {
      "name": "Fumble",
      "category": "Sitting & Kneeling",
      "deep_penetration": 3,
      "penetration_control": "shared",
      "g_spot_stimulation": 2,
      "clitoral_stimulation": 3,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 4,
      "lower_back_load": 4,
      "knee_load": 3,
      "shoulder_wrist_load": 4,
      "neck_load": 1,
      "flexibility_required": "high",
      "overweight_suitability": 1,
      "pregnancy_suitability": "not_suitable",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": false,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "poor",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "medium",
      "premature_ejaculation_suitability": "medium",
      "eye_contact_intimacy": 3,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "intermediate",
      "note": "Improvised, irregular fast-paced variant; not overly advanced despite acrobatic family.",
      "photopath": "./positions/fumble/fumble.png"
    },
    {
      "name": "Wide Receiver",
      "category": "Man on Top",
      "deep_penetration": 4,
      "penetration_control": "male",
      "g_spot_stimulation": 5,
      "clitoral_stimulation": 2,
      "condom_slip_risk": "medium",
      "male_effort": 4,
      "female_effort": 2,
      "lower_back_load": 3,
      "knee_load": 4,
      "shoulder_wrist_load": 2,
      "neck_load": 1,
      "flexibility_required": "low",
      "overweight_suitability": 4,
      "pregnancy_suitability": "until_mid_pregnancy",
      "postpartum_recovery_suitability": false,
      "mobility_limitation_suitability": false,
      "pain_condition_recommended": true,
      "vaginismus_dyspareunia_suitability": "poor",
      "erectile_difficulty_suitability": "good",
      "long_penis_suitability": "medium",
      "short_penis_suitability": "good",
      "premature_ejaculation_suitability": "poor",
      "eye_contact_intimacy": 1,
      "kissing_possible": false,
      "communication_ease": 2,
      "privacy_noise_level": "medium",
      "equipment_needed": "none",
      "experience_level": "beginner",
      "note": "",
      "photopath": "./positions/wide-receiver/wide-receiver.png"
    }
  ]
}